# Generated by Django 6.0.6 on 2026-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('aircraft_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_service_hours', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('MAINTENANCE_DUE', 'MAINTENANCE_DUE'), ('GROUNDED', 'GROUNDED'), ('IN_MAINTENANCE', 'IN_MAINTENANCE')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
