# Generated by Django 6.0.6 on 2026-06-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('engineer_name', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('hours_at_service', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_service_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft')),
            ],
        ),
    ]
